# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nnLJ0HQ6DYiiPrCBH-hPUex4ITEjsOg
"""

import streamlit as st
import requests
import random
from PIL import Image
from io import BytesIO

# 📂 Configuración del repositorio
OWNER = "jsfa2002"
REPO = "fotos_lindas"
IMAGE_PATH = "imagenesmYm"  # Ruta dentro del repo

# 🔹 Función optimizada para obtener imágenes (con caché)
@st.cache_data
def obtener_lista_imagenes():
    url = f"https://api.github.com/repos/{OWNER}/{REPO}/contents/{IMAGE_PATH}"
    response = requests.get(url)

    if response.status_code == 200:
        return [file["download_url"] for file in response.json() if file["name"].endswith((".png", ".jpg", ".jpeg"))]
    else:
        st.error(f"Error al obtener imágenes. Código {response.status_code}")
        return []

# 📷 Cargar imágenes
image_urls = obtener_lista_imagenes()

# 🏷 Mensaje superior
st.markdown("<h1 style='text-align: center; color: #ff66b2;'>🧚 Nuestras fotos ⛵</h1>", unsafe_allow_html=True)

if image_urls:
    if "img_index" not in st.session_state:
        st.session_state.img_index = random.randint(0, len(image_urls) - 1)

    col1, col2, col3 = st.columns([1, 3, 1])  # Centrar botón
    with col2:
        if st.button("💖 TE AMO 💖", use_container_width=True):
            st.session_state.img_index = random.randint(0, len(image_urls) - 1)

    # Descargar y mostrar la imagen
    response = requests.get(image_urls[st.session_state.img_index])
    if response.status_code == 200:
        image = Image.open(BytesIO(response.content))
        st.image(image, use_container_width=True)  # Se corrigió `use_column_width`
    else:
        st.error("No se pudo cargar la imagen.")

    # 🌸 Mensaje bonito centrado debajo de la imagen
    st.markdown("<h2 style='text-align: center; color: #ff66b2;'>Eres lo más bonito de mi mundo 🌸</h2>", unsafe_allow_html=True)
else:
    st.warning("No hay imágenes disponibles.")
